const config = require('@silvermine/eslint-config'),
      node = require('@silvermine/eslint-config/partials/node');

module.exports = [
   {
      ignores: [
         '**/dist/**',
         '**/dist-js/**',
         '**/.cache/**',
         '**/.temp/**',
         '**/temp/**',
         '**/api-iife.js',
         '**/node_modules/**',
         '**/target/**',
         '**/permissions/autogenerated/**',
         '**/*.config.js',
         '**/*.d.ts',
         '**/commitlint.config.cjs',
         'vitest.config.ts',
      ],
   },
   ...config,
   { ...node },
   {
      files: [ '**/*.ts' ],
      rules: {
         'no-console': [ 'error', { allow: [ 'debug', 'info', 'warn', 'error', 'table' ] } ],
         '@silvermine/eslint-plugin-silvermine/call-indentation': 'off',
      },
      languageOptions: {
         parserOptions: {
            project: [ 'tsconfig.src.json', 'tsconfig.test.json' ],
         },
      },
   },
];
